Update German translation
micheleg/dash-to-dock pull request #2282
Opened 2024-09-06 09:08 UTC by Amr-Ibra

### Note:

Poedit can delete many “unused translations”. The question is: is Poedit right? Are there really so many unused translations to delete? Have the original strings really got removed from the source code?

I haven't deleted any “unused translations” yet. But I can update this PR to delete them after confirmation from the developers that the original strings got removed from the source code.

2024-09-16 22:05 UTC, 3v1n0 commented
Mh, I feel something is wrong since some of the _deleted translations_ still seems to be used here.

2024-09-17 08:35 UTC, Amr-Ibra commented
`make mergepo` is the one to blame.

2024-12-11 20:45 UTC, xalt7x commented
@Amr-Ibra 
Somehow I've got incomplete file as well...    
You can just `rm po/dashtodock.pot`, then `make potfile`

2025-01-24 09:30 UTC, sergio-costas requested changes
A little change requested.

2025-01-24 09:32 UTC, sergio-costas commented
@3v1n0 @Amr-Ibra I had the same problem recently when working with DevedeNG: I found that intltool-update doesn't recognize the .ui files anymore, although before it did. That's why there are so many sentences marked as _deleted translations_.

2025-01-24 09:33 UTC, sergio-costas commented
I was able to fix it by using msgmerge, but that will require a change in the Makefile... I'll see what I can do.

2025-01-24 09:37 UTC, sergio-costas commented
Oh... the makefile doesn't use intltool-update, but msgmerge... forget what I said.

2025-01-24 21:06 UTC, Amr-Ibra commented on po/de.po
> +msgstr "%s wird gerade aktualisiert …"
Yes, it is intentional. In German, the ellipsis (triple points) should have a space before it.
https://en.wikipedia.org/wiki/Ellipsis#In_German

You can test the German text on LanguageTool. Try to delete the space before the ellipsis and see what LanguageTool suggests.
https://languagetool.org

2025-01-24 21:16 UTC, Amr-Ibra commented
> Somehow I've got incomplete file as well... You can just `rm po/dashtodock.pot`, then `make potfile`

I did that, and I think it fixed the problem. There aren't as many deleted translations as there were before I pushed my last change. I think it's safe to merge this PR now.

2025-01-27 09:05 UTC, sergio-costas commented on po/de.po
> +msgstr "%s wird gerade aktualisiert …"
Oh... perfect then.

2025-01-27 09:10 UTC, sergio-costas approved these changes
Looks fine to me, but somebody else should review it too.

2025-02-14 17:22 UTC, merged